triggers:
  push:
    events:
      - push
      - pull_request

jobs:
  build:
    docker:
      image: ubuntu
    steps:
      - echo "Building..."
      - echo "Done"
  test:
    docker:
      image: ubuntu
    steps:
      - echo "Testing..."
    depends-on:
      - build

